var automationframework = connect('localhost:27017/automationframework');
//Action IDs 
var CheckTextID = ObjectId();
var ClickElementID = ObjectId();
var CloseAppID = ObjectId();
var DriverID = ObjectId();
var GetTextID = ObjectId();
var InstallAppID = ObjectId();
var LongPressID = ObjectId();
var PinchID = ObjectId();
var ReLaunchAppID = ObjectId();
var RemoveAppID = ObjectId();
var ResetAppID = ObjectId();
var RotateScreenID = ObjectId();
var ScreenshotID = ObjectId();
var SetTextID = ObjectId();
var SleepID = ObjectId();
var SwipeDownID = ObjectId();
var SwipeDownSlowID = ObjectId();
var SwipeLeftID = ObjectId();
var SwipeLeftSlowID = ObjectId();
var SwipeRightID = ObjectId();
var SwipeRightSlowID = ObjectId();
var SwipeToFindElementID = ObjectId();
var SwipeUpID = ObjectId();
var SwipeUpSlowID = ObjectId();
var TapID = ObjectId();
var ZoomID = ObjectId();
var InterruptionID =ObjectId();

//Test Case IDs
var LaunchDriverTestCaseID = ObjectId();

//Test Set IDs
var LaunchTestSetID = ObjectId();

//Execution IDs
var LaunchDriverEXID = ObjectId();

//appium based actions

automationframework.actions.save({"_id":ReLaunchAppID,"tag":["appium"],"params":[],"name":"ReLaunch App","description":"This will Relaunch the app. ","type":"script","status":"Automated","collection":[],"script":"actions.ReLaunchApp.run","scriptLang":"Java/Groovy","project":projectName});
automationframework.actions.save({"_id":ResetAppID,"tag":["appium"],"params":[],"name":"Reset App","description":"This will Reset the Current running app using appiumdriver.","type":"script","status":"Automated","collection":[],"script":"actions.ResetApp.run","scriptLang":"Java/Groovy","project":projectName});
automationframework.actions.save({"_id":ZoomID,"tag":["appium"],"params":[{"name":"ID","description":"","possiblevalues":[],"parametertype":"String","id":"1475502965636-30706-9606"},{"name":"ID Type","description":"","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name","Android UI Automator","IOS UI Automator"],"parametertype":"String","id":"1475503102540-10550-5983"},{"name":"App Type","description":"","possiblevalues":["Android","IOS","Web","Hybrid"],"parametertype":"String","id":"1475657707430-6753-22192"}],"name":"Zoom","description":"This will zoom in the element if allowed.","type":"script","status":"Automated","collection":[],"script":"actions.Zoom.run","scriptLang":"Java/Groovy","project":projectName});
automationframework.actions.save({"_id":GetTextID,"tag":["appium"],"params":[{"name":"ID","description":"","possiblevalues":[],"parametertype":"String","id":"1475504640444-697-20963"},{"name":"ID Type","description":"","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name","Android UI Automator","IOS UI Automator"],"parametertype":"String","id":"1475504648948-22329-14314"},{"name":"App Type","description":"","possiblevalues":["Android","IOS","Web","Hybrid"],"parametertype":"String","id":"1475659682988-29904-30448"}],"name":"Get Text","description":"This will get the text from the element.","type":"script","status":"Automated","collection":[],"script":"actions.GetText.run","scriptLang":"Java/Groovy","project":projectName});
automationframework.actions.save({"_id":SetTextID,"tag":["appium"],"params":[{"name":"Text","description":"","possiblevalues":[],"parametertype":"String","id":"1475503531604-26481-11714"},{"name":"ID","description":"","possiblevalues":["nickName","//UIAApplication[1]/UIAWindow[1]/UIAScrollView[1]/UIATextField[1]"],"parametertype":"String","id":"1475504640444-697-20963"},{"name":"ID Type","description":"","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name","Android UI Automator","IOS UI Automator"],"parametertype":"String","id":"1475504648948-22329-14314"},{"name":"App Type","description":"","possiblevalues":["Android","IOS","Web","Hybrid"],"parametertype":"String","id":"1475659682988-29904-30448"}],"name":"Set Text","description":"This will used to write text in the EditText,Textfield etc.","type":"script","status":"Automated","collection":[],"script":"actions.SetText.run","scriptLang":"Java/Groovy","project":projectName});
automationframework.actions.save({"_id":DriverID,"tag":["appium"],"params":[{"name":"appDir","description":"","possiblevalues":[],"parametertype":"String","id":"1475489268802-2973-29207"},{"name":"appName","description":"","possiblevalues":["xyz.apk","xyz.app","xyz.ipa"],"parametertype":"String","id":"1475489391130-7724-25602"},{"name":"appPackage","description":"","possiblevalues":["com.dinkark.appium"],"parametertype":"String","id":"1475489814682-15764-32669"},{"name":"platform","description":"","possiblevalues":["Android","IOS"],"parametertype":"String","id":"1475489873235-26245-5208"},{"name":"OSversion","description":"","possiblevalues":["4.4","5.0","5.1","6.0","9.3","10.0","7.0"],"parametertype":"String","id":"1475489935618-6812-17781"},{"name":"deviceName","description":"","possiblevalues":["iPhone 6","Nexus 5X API 23"],"parametertype":"String","id":"1475489992674-16951-4078"},{"name":"launchActivity","description":"","possiblevalues":[".views.activities.SplashActivity"],"parametertype":"String","id":"1475490069770-16765-16975"},{"name":"noReset","description":"","possiblevalues":["true","false"],"parametertype":"String","id":"1475503990005-19623-16461"},{"name":"appiumNodeUrl","description":"","possiblevalues":["http://127.0.0.1:4723/wd/hub"],"parametertype":"String","id":"1475666151549-12284-11919"},{"name":"udid","description":"","possiblevalues":[],"parametertype":"String","id":"1476349075267-32501-21771"}],"name":"Initialize Driver","description":"This will initialize the Appium driver with provided capabilities.","type":"script","status":"Automated","collection":[],"script":"actions.Driver.run","scriptLang":"Java/Groovy","project":projectName});
automationframework.actions.save({"_id":PinchID,"tag":["appium"],"params":[{"name":"ID","description":"","possiblevalues":[],"parametertype":"String","id":"1475502965636-30706-9606"},{"name":"ID Type","description":"","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name","Android UI Automator","IOS UI Automator"],"parametertype":"String","id":"1475503102540-10550-5983"},{"name":"App Type","description":"","possiblevalues":["Android","IOS","Web","Hybrid"],"parametertype":"String","id":"1475657707430-6753-22192"}],"name":"Pinch","description":"This will pinch or zoom out the element if allowed.","type":"script","status":"Automated","collection":[],"script":"actions.Pinch.run","scriptLang":"Java/Groovy","project":projectName});
automationframework.actions.save({"_id":LongPressID,"tag":["appium"],"params":[{"name":"ID","description":"","possiblevalues":[],"parametertype":"String","id":"1475502965636-30706-9606"},{"name":"ID Type","description":"","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name","Android UI Automator","IOS UI Automator"],"parametertype":"String","id":"1475503102540-10550-5983"},{"name":"App Type","description":"","possiblevalues":["Android","IOS","Web","Hybrid"],"parametertype":"String","id":"1475657707430-6753-22192"}],"name":"Long press","description":"This will long press the element.","type":"script","status":"Automated","collection":[],"script":"actions.LongPress.run","scriptLang":"Java/Groovy","project":projectName});
automationframework.actions.save({"_id":SwipeRightSlowID,"tag":["appium"],"params":[{"name":"ID","description":"","possiblevalues":[],"parametertype":"String","id":"1475502965636-30706-9606"},{"name":"ID Type","description":"","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name","Android UI Automator","IOS UI Automator"],"parametertype":"String","id":"1475503102540-10550-5983"},{"name":"App Type","description":"","possiblevalues":["Android","IOS","Web","Hybrid"],"parametertype":"String","id":"1475657707430-6753-22192"},{"name":"no_of_times","description":"","possiblevalues":[],"parametertype":"String","id":"1476424616940-28397-17728"}],"name":"Swipe Right Slowly","description":"This will swipe right slowly(scroll small portion of view at a time) the scrollable element no of times you want.","type":"script","status":"Automated","collection":[],"script":"actions.SwipeRightSlow.run","scriptLang":"Java/Groovy","project":projectName});
automationframework.actions.save({"_id":CheckTextID,"tag":["appium"],"params":[{"name":"ID","description":"","possiblevalues":[],"parametertype":"String","id":"1475502965636-30706-9606"},{"name":"ID Type","description":"","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name","Android UI Automator","IOS UI Automator"],"parametertype":"String","id":"1475503102540-10550-5983"},{"name":"App Type","description":"","possiblevalues":["Android","IOS","Web","Hybrid"],"parametertype":"String","id":"1475657707430-6753-22192"},{"name":"Text","description":"","possiblevalues":[],"parametertype":"String","id":"1476423024748-16896-9991"}],"name":"Check Text","description":"This Will check the text of a particular element with the text you have provided in \"Text\" parameter in Test Case.","type":"script","status":"Automated","collection":[],"script":"actions.CheckText.run","scriptLang":"Java/Groovy","project":projectName});
automationframework.actions.save({"_id":ClickElementID,"tag":["appium"],"params":[{"name":"ID","description":"","possiblevalues":[],"parametertype":"String","id":"1475502965636-30706-9606"},{"name":"ID Type","description":"","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name","Android UI Automator","IOS UI Automator"],"parametertype":"String","id":"1475503102540-10550-5983"},{"name":"App Type","description":"","possiblevalues":["Android","IOS","Web","Hybrid"],"parametertype":"String","id":"1475657707430-6753-22192"}],"name":"Click Element","description":"This will click on the element found using \"ID\"(Identifier)  and Identifier Type like XPath,Class Name etc. ","type":"script","status":"Automated","collection":[],"script":"actions.ClickElement.run","scriptLang":"Java/Groovy","project":projectName});
automationframework.actions.save({"_id":CloseAppID,"tag":["appium"],"params":[],"name":"Close App","description":"This will close the app currently running through appium driver with specified capabilities.","type":"script","status":"Automated","collection":[],"script":"actions.CloseApp.run","scriptLang":"Java/Groovy","project":projectName});
automationframework.actions.save({"_id":InstallAppID,"tag":["appium"],"params":[{"name":"appPath","description":"","possiblevalues":[],"parametertype":"String","id":"1475503364796-10469-18999"}],"name":"Install App","description":"This will install the app present on the \"appPath\" location on currently running device/emulator/simulator with appium capabilities.   ","type":"script","status":"Automated","collection":[],"script":"actions.InstallApp.run","scriptLang":"Java/Groovy","project":projectName});
automationframework.actions.save({"_id":RemoveAppID,"tag":["appium"],"params":[{"name":"bundleId","description":"","possiblevalues":["com.dinkark.appium"],"parametertype":"String","id":"1475503297180-25542-12840"}],"name":"Remove App","description":"This will remove the app from the device/simulator/emulator using the \"bundleId\".","type":"script","status":"Automated","collection":[],"script":"actions.RemoveApp.run","scriptLang":"Java/Groovy","project":projectName});
automationframework.actions.save({"_id":RotateScreenID,"tag":["appium"],"params":[{"name":"orientation","description":"","possiblevalues":["landscape","portrait"],"parametertype":"String","id":"1475503619172-926-15580"}],"name":"Rotate Screen","description":"This will simulate the rotation. ","type":"script","status":"Automated","collection":[],"script":"actions.RotateScreen.run","scriptLang":"Java/Groovy","project":projectName});
automationframework.actions.save({"_id":SleepID,"tag":["appium"],"params":[{"name":"millis","description":"","possiblevalues":["5000"],"parametertype":"String","id":"1475661120244-12382-12843"}],"name":"Sleep","description":"This can be used to sleep the current Thread.","type":"script","status":"Automated","collection":[],"script":"actions.Sleep.run","scriptLang":"Java/Groovy","project":projectName});
automationframework.actions.save({"_id":SwipeDownID,"tag":["appium"],"params":[{"name":"ID","description":"","possiblevalues":[],"parametertype":"String","id":"1475502965636-30706-9606"},{"name":"ID Type","description":"","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name","Android UI Automator","IOS UI Automator"],"parametertype":"String","id":"1475503102540-10550-5983"},{"name":"App Type","description":"","possiblevalues":["Android","IOS","Web","Hybrid"],"parametertype":"String","id":"1475657707430-6753-22192"},{"name":"no_of_times","description":"","possiblevalues":[],"parametertype":"String","id":"1476423611403-152-12977"}],"name":"Swipe Down","description":"This will swipe down the scrollable element no of times you want.","type":"script","status":"Automated","collection":[],"script":"actions.SwipeDown.run","scriptLang":"Java/Groovy","project":projectName});
automationframework.actions.save({"_id":SwipeDownSlowID,"tag":["appium"],"params":[{"name":"ID","description":"","possiblevalues":[],"parametertype":"String","id":"1475502965636-30706-9606"},{"name":"ID Type","description":"","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name","Android UI Automator","IOS UI Automator"],"parametertype":"String","id":"1475503102540-10550-5983"},{"name":"App Type","description":"","possiblevalues":["Android","IOS","Web","Hybrid"],"parametertype":"String","id":"1475657707430-6753-22192"},{"name":"no_of_times","description":"","possiblevalues":[],"parametertype":"String","id":"1476423611403-152-12977"}],"name":"Swipe Down Slowly","description":"This will swipe down slowly(scroll small portion of view at a time) the scrollable element no of times you want.","type":"script","status":"Automated","collection":[],"script":"actions.SwipeDownSlow.run","scriptLang":"Java/Groovy","project":projectName});
automationframework.actions.save({"_id":SwipeLeftID,"tag":["appium"],"params":[{"name":"ID","description":"","possiblevalues":[],"parametertype":"String","id":"1475502965636-30706-9606"},{"name":"ID Type","description":"","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name","Android UI Automator","IOS UI Automator"],"parametertype":"String","id":"1475503102540-10550-5983"},{"name":"App Type","description":"","possiblevalues":["Android","IOS","Web","Hybrid"],"parametertype":"String","id":"1475657707430-6753-22192"},{"name":"no_of_times","description":"","possiblevalues":[],"parametertype":"String","id":"1476424608443-23750-11975"}],"name":"Swipe Left","description":"This will swipe left the scrollable element no of times you want.","type":"script","status":"Automated","collection":[],"script":"actions.SwipeLeft.run","scriptLang":"Java/Groovy","project":projectName});
automationframework.actions.save({"_id":SwipeLeftSlowID,"tag":["appium"],"params":[{"name":"ID","description":"","possiblevalues":[],"parametertype":"String","id":"1475502965636-30706-9606"},{"name":"ID Type","description":"","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name","Android UI Automator","IOS UI Automator"],"parametertype":"String","id":"1475503102540-10550-5983"},{"name":"App Type","description":"","possiblevalues":["Android","IOS","Web","Hybrid"],"parametertype":"String","id":"1475657707430-6753-22192"},{"name":"no_of_times","description":"","possiblevalues":[],"parametertype":"String","id":"1476424608443-23750-11975"}],"name":"Swipe Left Slowly","description":"This will swipe left slowly(scroll small portion of view at a time) the scrollable element no of times you want.","type":"script","status":"Automated","collection":[],"script":"actions.SwipeLeftSlow.run","scriptLang":"Java/Groovy","project":projectName});
automationframework.actions.save({"_id":SwipeUpSlowID,"tag":["appium"],"params":[{"name":"ID","description":"","possiblevalues":[],"parametertype":"String","id":"1475502965636-30706-9606"},{"name":"ID Type","description":"","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name","Android UI Automator","IOS UI Automator"],"parametertype":"String","id":"1475503102540-10550-5983"},{"name":"App Type","description":"","possiblevalues":["Android","IOS","Web","Hybrid"],"parametertype":"String","id":"1475657707430-6753-22192"},{"name":"no_of_times","description":"","possiblevalues":[],"parametertype":"String","id":"1476424639597-25355-24904"}],"name":"Swipe Up Slowly","description":"This will swipe up slowly(scroll small portion of view at a time) the scrollable element no of times you want.","type":"script","status":"Automated","collection":[],"script":"actions.SwipeUpSlow.run","scriptLang":"Java/Groovy","project":projectName});
automationframework.actions.save({"_id":SwipeRightID,"tag":["appium"],"params":[{"name":"ID","description":"","possiblevalues":[],"parametertype":"String","id":"1475502965636-30706-9606"},{"name":"ID Type","description":"","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name","Android UI Automator","IOS UI Automator"],"parametertype":"String","id":"1475503102540-10550-5983"},{"name":"App Type","description":"","possiblevalues":["Android","IOS","Web","Hybrid"],"parametertype":"String","id":"1475657707430-6753-22192"},{"name":"no_of_times","description":"","possiblevalues":[],"parametertype":"String","id":"1476424616940-28397-17728"}],"name":"Swipe Right","description":"This will swipe right the scrollable element no of times you want.","type":"script","status":"Automated","collection":[],"script":"actions.SwipeRight.run","scriptLang":"Java/Groovy","project":projectName});
automationframework.actions.save({"_id":SwipeUpID,"tag":["appium"],"params":[{"name":"ID","description":"","possiblevalues":[],"parametertype":"String","id":"1475502965636-30706-9606"},{"name":"ID Type","description":"","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name","Android UI Automator","IOS UI Automator"],"parametertype":"String","id":"1475503102540-10550-5983"},{"name":"App Type","description":"","possiblevalues":["Android","IOS","Web","Hybrid"],"parametertype":"String","id":"1475657707430-6753-22192"},{"name":"no_of_times","description":"","possiblevalues":[],"parametertype":"String","id":"1476424639597-25355-24904"}],"name":"Swipe Up","description":"This will swipe up the scrollable element no of times you want.","type":"script","status":"Automated","collection":[],"script":"actions.SwipeUp.run","scriptLang":"Java/Groovy","project":projectName});
automationframework.actions.save({"_id":SwipeToFindElementID,"tag":["appium"],"params":[{"name":"ID","description":"","possiblevalues":[],"parametertype":"String","id":"1475502965636-30706-9606"},{"name":"ID Type","description":"","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name","Android UI Automator","IOS UI Automator"],"parametertype":"String","id":"1475503102540-10550-5983"},{"name":"App Type","description":"","possiblevalues":["Android","IOS","Web","Hybrid"],"parametertype":"String","id":"1475657707430-6753-22192"},{"name":"Searching Element App Type","description":"","possiblevalues":["Android","IOS","Web","Hybrid"],"parametertype":"String","id":"1476361324034-28673-141"},{"name":"Searching Element ID Type","description":"","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name","Android UI Automator","IOS UI Automator"],"parametertype":"String","id":"1476361439186-7504-8028"},{"name":"Searching Element ID","description":"","possiblevalues":[],"parametertype":"String","id":"1476361527890-30767-13635"},{"name":"no_of_times","description":"","possiblevalues":[],"parametertype":"String","id":"1476361584275-8209-21059"},{"name":"Direction","description":"","possiblevalues":["up","down","right","left"],"parametertype":"String","id":"1476362971515-6404-12361"}],"name":"Swipe to Find Element","description":"This will swipe the scrollable element no of times you want and find the element if present.","type":"script","status":"Automated","collection":[],"script":"actions.SwipeToFindElement.run","scriptLang":"Java/Groovy","project":projectName});
automationframework.actions.save({"_id":ScreenshotID,"tag":["appium"],"params":[{"name":"Path for screenshot","description":"","possiblevalues":[],"parametertype":"String","id":"1476422581843-8633-27197"},{"name":"Screenshot name","description":"","possiblevalues":[],"parametertype":"String","id":"1476422619708-11279-11967"}],"name":"Take Screenshot","description":"This take screenshot of the device with name you specify and path where you want to save it.","type":"script","status":"Automated","collection":[],"script":"actions.Screenshot.run","scriptLang":"Java/Groovy","project":projectName});
automationframework.actions.save({"_id":TapID,"tag":["appium"],"params":[{"name":"ID","description":"","possiblevalues":[],"parametertype":"String","id":"1475502965636-30706-9606"},{"name":"ID Type","description":"","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name","Android UI Automator","IOS UI Automator"],"parametertype":"String","id":"1475503102540-10550-5983"},{"name":"App Type","description":"","possiblevalues":["Android","IOS","Web","Hybrid"],"parametertype":"String","id":"1475657707430-6753-22192"}],"name":"Tap Element","description":"This will tap on the element found using \"ID\"(Identifier)  and Identifier Type like XPath,Class Name etc. ","type":"script","status":"Automated","collection":[],"script":"actions.Tap.run","scriptLang":"Java/Groovy","project":projectName});
automationframework.actions.save({"_id":InterruptionID,"tag":["appium"],"params":[{"name":"ANDROID_HOME","description":"","possiblevalues":["/Users/dinkark/Library/Android/sdk"],"parametertype":"String","id":"1476947848170-23721-12750"},{"name":"udid","description":"","possiblevalues":["192.168.56.101:5555"],"parametertype":"String","id":"1476947894339-20321-11424"}],"name":"Make Android Interruption","description":"This will make a interruption","type":"script","status":"Automated","collection":[],"script":"actions.MakeAndroidInterruption.run","scriptLang":"Java/Groovy","date":null,"project":projectName});


//appium based testcases
automationframework.testcases.save({"_id":LaunchDriverTestCaseID,"tag":["appium"],"name":"Launch Driver","description":"This will launch your app in your emulator or simulator or device as per capabilities defined","status":"Automated","collection":[{"order":"1","actionid":DriverID.str,"host":"Default","executionflow":"Record Error Stop Test Case","returnvalue":"","parameters":[{"paramname":"appDir","parametertype":"String","paramid":"1475489268802-2973-29207","paramvalue":"/Documents/eclipse/workspace/AppiumTest/app/iOS/"},{"paramname":"appName","parametertype":"String","paramid":"1475489391130-7724-25602","paramvalue":"xyz.app"},{"paramname":"appPackage","parametertype":"String","paramid":"1475489814682-15764-32669","paramvalue":"com.dinkark.appium"},{"paramname":"platform","parametertype":"String","paramid":"1475489873235-26245-5208","paramvalue":"IOS"},{"paramname":"OSversion","parametertype":"String","paramid":"1475489935618-6812-17781","paramvalue":"9.3"},{"paramname":"deviceName","parametertype":"String","paramid":"1475489992674-16951-4078","paramvalue":"iPhone 6"},{"paramname":"launchActivity","parametertype":"String","paramid":"1475490069770-16765-16975","paramvalue":"<NULL>"},{"paramname":"noReset","parametertype":"String","paramid":"1475503990005-19623-16461","paramvalue":"true"},{"paramname":"appiumNodeUrl","parametertype":"String","paramid":"1475666151549-12284-11919","paramvalue":"http://127.0.0.1:4723/wd/hub"},{"paramname":"udid","parametertype":"String","paramid":"1476349075267-32501-21771","paramvalue":"<NULL>"}]}],"tcData":[],"rowIndex":0,"script":"actions.OpenDriver.run","scriptLang":"Java/Groovy","host":"","type":"collection","afterState":[],"project":projectName});
//appium based testsets
automationframework.testsets.save({"_id":LaunchTestSetID,"name":"LaunchTestSet","testcases":[{"_id":LaunchDriverTestCaseID.str}],"project":projectName});
//appium based executions
automationframework.executions.save({"_id":LaunchDriverEXID,"name":"Launch Driver  Demo","status":"Ready To Run","emails":["dinkar.kumar@talentica.com"],"locked":false,"ignoreStatus":false,"allScreenshots":false,"ignoreAfterState":false,"testset":LaunchTestSetID.str,"resultID":"","baseStateTCID":"","testsetname":"LaunchTestSet","tag":[],"variables":[],"machines":[{"host":"127.0.0.1","vncport":"3006","port":"5009","maxThreads":4,"threads":1,"tag":[""],"state":"","baseState":"","resultID":"","baseStateTCID":"1475734216047-27552-31449","result":"","description":"host name is:RealSociable","machineVars":[],"roles":["Default"],"_id":"5763c98be7e19e540b000001"},{"host":"172.19.129.125","vncport":"3006","port":"5009","maxThreads":1,"threads":1,"tag":[""],"state":"","baseState":"","resultID":"","baseStateTCID":"1475734216047-18334-1150","result":"","description":"host name is:dinkark-mac.local","machineVars":[],"roles":["Default"],"_id":"57eb9842451e2fc40385a42b"}],"lastRunDate":null,"runtime":0,"passed":0,"failed":0,"total":1,"notRun":1,"project":projectName});

//tags
automationframework.actionTags.save({"value":"appium","project":projectName,"_id":ObjectId()});

automationframework.testcaseTags.save({"value":"appium","project":projectName,"_id":ObjectId()});
//execution test cases
automationframework.executiontestcases.save({"_id":ObjectId().str,"name":"Launch Device","tag":["appium"],"status":"Not Run","host":"","vncport":"","resultID":"","result":"","startdate":null,"enddate":null,"runtime":"","error":"","testcaseID":LaunchDriverTestCaseID.str,"executionID":LaunchDriverEXID.str,"project":projectName});